services:
  yuki:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: yuki-dev
    ports:
      - "3315:3315"
    volumes:
      - .:/app/Yuki
      - /Users/wave/workdir/Celebi/Celebi/CelebiChrono:/app/CelebiChrono
      - yuki-storage:/root/.Yuki
    environment:
      - FLASK_ENV=development
      - CELERY_BROKER_URL=amqp://localhost
    working_dir: /app
    stdin_open: true
    tty: true

volumes:
  yuki-storage:
